-- 0023 — Industry Playbook System
-- Agency-level reference playbooks per industry (campaign ideas, topic library,
-- seasonal content, subject lines, CTAs). Consulted by the Strategy Engine when a
-- client's industry matches. Generated by Claude, refinable, latest row per industry.

create table public.industry_playbooks (
  id          uuid primary key default gen_random_uuid(),
  agency_id   uuid not null references public.agencies(id) on delete cascade,
  industry    text not null,
  payload     jsonb not null default '{}'::jsonb,
  created_by  uuid references public.profiles(id) on delete set null,
  created_at  timestamptz not null default now()
);
create index industry_playbooks_idx on public.industry_playbooks(agency_id, industry, created_at desc);

alter table public.industry_playbooks enable row level security;
create policy industry_playbooks_staff_all on public.industry_playbooks
  for all using (agency_id = public.current_agency_id() and public.is_agency_staff())
  with check (agency_id = public.current_agency_id() and public.is_agency_staff());
